SEED: 223

DATASET:
  datadir: /datasets

OPTIMIZER:
  opt_name: Adam
  lr: 0.001

TRAINING:
  batch_size: 256
  test_batch_size: 256
  epochs: 100
  log_interval: 10
  use_scheduler: true

RESULT:
  savedir: './saved_model'