EXP_NAME: 'densenet121-finetune_set'
SEED: 223

MODEL:
  modelname: densenet121
  num_classes: 10
  
DATASET:
  datadir: /datasets
  dataname: CIFAR10
  mean:
    - 0.4914
    - 0.4822
    - 0.4465
  std:
    - 0.2470
    - 0.2435
    - 0.2616

OPTIMIZER:
  opt_name: Adam
  lr: 0.001

TRAINING:
  batch_size: 256
  test_batch_size: 256
  epochs: 50
  log_interval: 10
  use_scheduler: true

RESULT:
  savedir: './saved_model'