EXP_NAME: 'resnet18-pretrained_set'
SEED: 223

MODEL:
  modelname: resnet18
  num_classes: 10
  
DATASET:
  datadir: /datasets
  dataname: CIFAR10

OPTIMIZER:
  opt_name: Adam
  lr: 0.001

TRAINING:
  batch_size: 256
  test_batch_size: 256
  epochs: 50
  log_interval: 10
  use_scheduler: true

RESULT:
  savedir: './saved_model'